### ISSUE TITLE
Docker: seems not to work out of the box

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius-Standard#256]
Basically used `create-project` using `dev-master`, cd'ed into the box, ran `docker-compose up -d`, pointing browser to `localhost:80` results in:

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1044] Access denied for user 'sylius'@'%' to database 'sylius' in /srv/sylius/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:46 Stack trace: #0 /srv/sylius/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(46): PDO->__construct('mysql:host=mysq...', 'sylius', 'nopassword', Array) #1 /srv/sylius/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(44): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=mysq...', 'sylius', 'nopassword', Array) #2 /srv/sylius/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'sylius', 'nopassword', Array) #3 /srv/sylius/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(921): Doctrine\DBAL\Connection->connect() #4 /srv/sylius/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(733): Doctrine\DBAL\Connection->executeQuery('SELECT t0.code ...', Array, Array) #5 /srv/sylius/vendor/doctrine/orm/lib/ in /srv/sylius/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 113
```

Haven't been digging further yet though.

**Comment by pamil** [comment]
Could you try again next week with `v1.3.1` release?

**Comment by jacquesbh** [comment]
Ping @stefandoorn

Can you try again please? It should work now.

**Comment by stefandoorn** [comment]
```
git clone git@github.com:Sylius/Sylius-Standard.git Sylius-Docker
cd Sylius-Docker
docker-compose up -d
```

So, testing it on `dev-master`. Then eventually it runs into another error right now:

```
...
Step 23/29 : RUN set -eux; 	mkdir -p var/cache var/log; 	composer dump-autoload --classmap-authoritative; 	composer run-script post-install-cmd; 	chmod +x bin/console; sync; 	bin/console sylius:install:assets; 	bin/console sylius:theme:assets:install public
 ---> Running in 17b91e2122b9
+ mkdir -p var/cache var/log
+ composer dump-autoload --classmap-authoritative
Generating optimized autoload files (authoritative)
+ composer run-script post-install-cmd
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!   // Clearing the cache for the prod environment with debug                      
!!   // false                                                                       
!!  
!!  
!!  In EnvVarProcessor.php line 77:
!!                                                   
!!    Environment variable not found: "APP_SECRET".  
!!                                                   
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
!!  
!!  
Script @auto-scripts was called via post-install-cmd
ERROR: Service 'php' failed to build: The command '/bin/sh -c set -eux; 	mkdir -p var/cache var/log; 	composer dump-autoload --classmap-authoritative; 	composer run-script post-install-cmd; 	chmod +x bin/console; sync; 	bin/console sylius:install:assets; 	bin/console sylius:theme:assets:install public' returned a non-zero code: 1
```

**Comment by stefandoorn** [comment]
Another method try, after stopping/removing the previous run (including volumes):

```
php -d memory_limit=-1 /usr/local/bin/composer create-project sylius/sylius-standard Sylius-Docker --ignore-platform-reqs
cd Sylius-Docker
docker-compose up -d --force-recreate --build # make sure its new
```

As I got locally PHP 7.1 installed still, I have to add this `ignore-platform-reqs` to make sure I get Sylius v1.3 installed (as it requires PHP 7.2). I hardly ever do things local (all in VM's), therefore. I actually think I should not use `create-project`, but the docs state nothing about how to work with Docker in this case.

It asks me in the meanwhile for all kind of ENV vars which I have no clue about what they need to be for Docker (no instructions anywhere out of the box). I just press ENTER on all of them for now.

Wait a bit..:

```
502 Bad Gateway
nginx/1.15.3
```

From container logs:

```
2018/10/27 14:37:23 [error] 5#5: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.4:9000", host: "localhost"
```

Then into the PHP container to verify whether things look properly in there:

```
/srv/sylius # bin/console 
Symfony 4.1.6 (kernel: src, env: dev, debug: true)

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -e, --env=ENV         The Environment name. [default: "dev"]
      --no-debug        Switches off debug mode.
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug


In FileSystemLocator.php line 118:
                                                                   
  Root image path not resolvable "/srv/sylius/public/media/image"  
                                                                   

list [--raw] [--format FORMAT] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] [<command> [<namespace>]]
```

**Comment by stefandoorn** [comment]
@teohhanhui You got any clue on this?

**Comment by teohhanhui** [comment]
I'll take a look.

**Comment by xwillie** [comment]
I did this as a work around:

`docker exec -it [CONTAINERNAME] mkdir -p /srv/sylius/public/media/image`

After this i am able to run any commands like installing Sylius e.g.

`docker exec -it [CONTAINERNAME] bin/console sylius:install`

**Comment by teohhanhui** [comment]
@stefandoorn I cannot reproduce any of the errors you've mentioned. I suspect it must be a problem specific to your environment / machine.

**Comment by teohhanhui** [comment]
Uhh, I see now. It was "fixed" in https://github.com/Sylius/Sylius-Standard/pull/286. I'll take another look. That didn't seem like a good fix at all... :see_no_evil:
