### ISSUE TITLE
Cannot run vendor/bin/ecs on default Docker setup for Sylius

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius-Standard#397]
Steps to reproduce:
 - `git clone git@github.com:Sylius/Sylius-Standard.git`
 - `docker-compose up`
 - wait for it to build
![image](https://user-images.githubusercontent.com/5156054/80288590-86a7f680-8741-11ea-99ec-7d9a92f72c4e.png)
 - docker-compose exec php sh
 - vendor/bin/ecs

What happens:
you receive the error below:
```
/srv/sylius # vendor/bin/ecs 

Fatal error: Uncaught TypeError: Return value of Nette\Utils\Strings::toAscii() must be of the type string, bool returned in /srv/sylius/vendor/nette/utils/src/Utils/Strings.php:183
Stack trace:
#0 /srv/sylius/vendor/nette/utils/src/Utils/Strings.php(192): Nette\Utils\Strings::toAscii(false)
#1 /srv/sylius/vendor/symplify/easy-coding-standard/packages/ChangedFilesDetector/src/CompilerPass/AddGetCwdWebalizedParameterCompilerPass.php(13): Nette\Utils\Strings::webalize('/srv/sylius')
#2 /srv/sylius/vendor/symfony/dependency-injection/Compiler/Compiler.php(94): Symplify\EasyCodingStandard\ChangedFilesDetector\CompilerPass\AddGetCwdWebalizedParameterCompilerPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#3 /srv/sylius/vendor/symfony/dependency-injection/ContainerBuilder.php(762): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#4 /srv/sylius/vendor/symfony/http-kernel/Kernel.php(599): Symfony\Component\DependencyInje in /srv/sylius/vendor/nette/utils/src/Utils/Strings.php on line 183
/srv/sylius # 
```

What should happen:
You should be able to run the command without any problems.

Related:
 - https://github.com/docker-library/php/issues/240

Notes:
As a tip from @tanasecosminromeo I added the line below to my docker setup and this automagically fixed the issue:

```
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
```

**Comment by maciekpaprocki** [comment]
This issue is now fixed I believe, at least works for me.

**Comment by gabiudrescu** [comment]
yup, I can confirm, cannot reproduce anymore.
