### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by AndreyEQ** [Sylius/Sylius-Standard#48]
OS Ububtu Server 14.04
RAM: 1 Gb

```sh
devel@server:~$ php composer.phar create-project sylius/sylius-standard -s dev
Installing sylius/sylius-standard (dev-master 050c336ed8b9b5fa9ce9b499a29cf4768b76b1bc)
  - Installing sylius/sylius-standard (dev-master master)
    Cloning master

Created project in /home/devel/sylius-standard
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing psr/log (1.0.0)
    Loading from cache
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///home/devel/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:983
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_open(): fo...', 'phar:///home/de...', 983, Array)
#1 phar:///home/devel/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(983): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 phar:///home/devel/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(799): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///home/devel/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(760): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///home/devel/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(690): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar:///home/de in phar:///home/devel/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php on line 983

Fatal error: Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///home/devel/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:983
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_open(): fo...', 'phar:///home/de...', 983, Array)
#1 phar:///home/devel/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(983): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 phar:///home/devel/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(799): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///home/devel/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(760): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///home/devel/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(690): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar:///home/de in phar:///home/devel/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php on line 983
```

**Comment by michalmarcinkowski** [comment]
Hope you managed to resolved the issue, please reopen if still relevant.
