### ISSUE TITLE
Swiftmailer should be removed in favor of symfony mailer in 1.12

### ISSUE THREAD

**Issue by vasilvestre** [Sylius/Sylius-Standard#841]

**Comment by gabiudrescu** [comment]
running `docker-compose -f docker-compose.prod.yml` up will generate this error:

```
 ---> Running in 6ed2614a95c2
+ mkdir -p var/cache var/log
+ composer dump-autoload --classmap-authoritative
Generating optimized autoload files (authoritative)
Class Payum\Be2Bill\Tests\Be2billOffsiteGatewayFactoryTest located in ./vendor/payum/payum/src/Payum/Be2Bill/Tests/Be2BillOffsiteGatewayFactoryTest.php does not comply with psr-4 autoloading standard. Skipping.
Generated optimized autoload files (authoritative) containing 12173 classes
+ APP_SECRET= composer run-script post-install-cmd

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  
!!  Fatal error: Uncaught Error: Class "Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle" not found in /srv/sylius/src/Kernel.php:45
!!  Stack trace:
!!  #0 /srv/sylius/vendor/symfony/http-kernel/Kernel.php(386): App\Kernel->registerBundles()
!!  #1 /srv/sylius/vendor/symfony/http-kernel/Kernel.php(786): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /srv/sylius/vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()
!!  #3 /srv/sylius/vendor/symfony/framework-bundle/Console/Application.php(168): Symfony\Component\HttpKernel\Kernel->boot()
!!  #4 /srv/sylius/vendor/symfony/framework-bundle/Console/Application.php(74): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #5 /srv/sylius/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #6 /srv/sylius/bin/console(38): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
!!  #7 {main}
!!    thrown in /srv/sylius/src/Kernel.php on line 45
!!  
Script @auto-scripts was called via post-install-cmd
The command '/bin/sh -c set -eux;     mkdir -p var/cache var/log;     composer dump-autoload --classmap-authoritative;     APP_SECRET='' composer run-script post-install-cmd;     chmod +x bin/console; sync;     bin/console sylius:install:assets --no-interaction;     bin/console sylius:theme:assets:install public --no-interaction' returned a non-zero code: 255
ERROR: Service 'php' failed to build : Build failed
```

**Comment by vasilvestre** [comment]
May be fixed at https://github.com/Sylius/Sylius-Standard/pull/848
